import type { Metadata } from "next";
import "../globals.css";
import { AppSidebar } from "@/components/app-sidebar";

import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import Header from "@/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased font-nanum`}>
        <SidebarProvider>
          <AppSidebar />
          <main className="w-full">
            <SidebarInset>
              <Header />
              {children}
            </SidebarInset>
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
